# Generated by Django 5.1.3 on 2025-05-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLanguage',
            fields=[
                ('language_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default=None, max_length=11)),
                ('bio', models.TextField(default=None, max_length=500)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('batchYear', models.CharField(choices=[('None', 'None'), ('UG-1', 'UG-1'), ('UG-2', 'UG-2'), ('UG-3', 'UG-3'), ('UG-4', 'UG-4'), ('MS', 'MS'), ('Ph.D', 'Ph.D')], default='None', max_length=4)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default=None, max_length=300)),
                ('has_read', models.BooleanField(default=False)),
                ('sending_time', models.DateTimeField(auto_now_add=True)),
                ('recieving_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgfrom', to='Portal.customuser')),
                ('_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgto', to='Portal.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default=None, max_length=300)),
                ('postedOn', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('task_count', models.IntegerField(default=0)),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project_type', models.CharField(choices=[('Fixed', 'Fixed Price'), ('Hourly', 'Hourly Rate')], default='Fixed', max_length=20)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry Level'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Intermediate', max_length=20)),
                ('project_duration', models.CharField(choices=[('Less than 1 month', 'Less than 1 month'), ('1 to 3 months', '1 to 3 months'), ('3 to 6 months', '3 to 6 months'), ('More than 6 months', 'More than 6 months')], default='1 to 3 months', max_length=30)),
                ('proposals_count', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkillsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(default=None, max_length=300)),
                ('deadline', models.DateField()),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('credits', models.CharField(choices=[('Academic', 'Academic'), ('Paid', 'Paid'), ('Other', 'Other')], default='Academic', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('mention', models.CharField(blank=True, default=None, max_length=100)),
                ('task_link', models.URLField(blank=True, default=None, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.project')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCreditVerified', models.BooleanField(default=False)),
                ('time_of_selection', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.customuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.task')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_application', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.customuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLanguagesRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluency_level_required', models.IntegerField(default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.communicationlanguage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSkillsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level_required', models.IntegerField(default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.skill')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.task')),
            ],
        ),
        migrations.CreateModel(
            name='UsersCommunicationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_fluency', models.IntegerField(default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.communicationlanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UsersSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_proficiency', models.IntegerField(default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.IntegerField(help_text='Delivery time in days')),
                ('cover_letter', models.TextField(max_length=1000)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Portal.project')),
            ],
            options={
                'unique_together': {('project', 'freelancer')},
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portal.task')),
                ('f_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('e_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_by', to='Portal.customuser')),
                ('fre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_to', to='Portal.customuser')),
            ],
        ),
    ]
