# Generated by Django on [timestamp]

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.IntegerField(help_text='Delivery time in days')),
                ('cover_letter', models.TextField(max_length=1000)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Portal.project')),
            ],
            options={
                'unique_together': {('project', 'freelancer')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSkillsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.skill')),
            ],
        ),
    ]