# Generated by Django on [timestamp]

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_add_missing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Fixed', 'Fixed Price'), ('Hourly', 'Hourly Rate')], default='Fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='experience_level',
            field=models.CharField(choices=[('Entry', 'Entry Level'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.CharField(choices=[('Less than 1 month', 'Less than 1 month'), ('1 to 3 months', '1 to 3 months'), ('3 to 6 months', '3 to 6 months'), ('More than 6 months', 'More than 6 months')], default='1 to 3 months', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='proposals_count',
            field=models.IntegerField(default=0),
        ),
    ]