# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_add_project_upwork_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(default='', max_length=300)),
                ('deadline', models.DateField()),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('credits', models.CharField(choices=[('Academic', 'Academic'), ('Paid', 'Paid'), ('Other', 'Other')], default='Academic', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('mention', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('task_link', models.URLField(blank=True, default='', max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.project')),
            ],
        ),
    ]