# Generated by Django 5.1.3 on 2025-06-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_recreate_task_dependent_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rated_user',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rating_user',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='review',
        ),
        migrations.AddField(
            model_name='userrating',
            name='e_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userrating',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_by', to='Portal.customuser'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='f_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userrating',
            name='fre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_to', to='Portal.customuser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='mention',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portal.task'),
        ),
    ]
