# Generated by Django 5.1.3 on 2025-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_project_project_status_projectfile_projectstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='access_level',
            field=models.CharField(choices=[('public', 'Available During Bidding'), ('private', 'Available After Hiring')], default='private', help_text='Choose when freelancers can access this file', max_length=20),
        ),
    ]
