# Generated by Django 5.1.3 on 2025-06-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0011_projectfile_access_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='projectfile',
            name='category',
            field=models.CharField(choices=[('requirement', 'Project Requirement'), ('reference', 'Reference Material'), ('example', 'Example Work'), ('specification', 'Technical Specification'), ('other', 'Other')], default='requirement', help_text='Categorize this file for better organization', max_length=30),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', help_text='Priority level of this file', max_length=20),
        ),
    ]
